### ISSUE TITLE
wrong button in vjoy

### ISSUE THREAD

**Issue by seelenkrieger** [grawsom/vJoyTP#2]
hey just found your usefull plugin for my flightsim
My problem is follow:
If I program button 2, it still press number1 in vjoy
![image](https://user-images.githubusercontent.com/55149789/119816184-b5684180-beec-11eb-94d3-1ce498816a61.png)

At the moment I'm not shure if I make a fault, or your plugin is faulty

**Comment by grawsom** [comment]
Seems like there is an bug - I'm looking into this

**Comment by grawsom** [comment]
What does the log show, i have this.
15:22:38.973 - [LOG] (Action Flow)  - Doing action: [Add a vJoy button] first -> 2 | second -> 10 | third -> On | 
15:22:38.973 - [LOG] (Plugin Instance) Executing: [REMOVED INFO]\AppData\Roaming\TouchPortal\plugins\vJoyTP\vJoyTP\vJoyTP.exe 1 1 On
It's like something was stuck in cache/memory.
I did remove the plugin, and installed it again - and now it's working as exspected.

**Comment by grawsom** [comment]
Or else continue on discord -https://discord.gg/SWRqueWT
